# -*- coding: utf-8 -*-
# vim: ft=yaml
---
prometheus:
  pkg:
    name: prometheus
    use_upstream_repo: False
    repo:
      humanname: prometheus
      name: prometheus
      comments:
        - installed by salt
      enabled: 1
      gpgcheck: 1
  rootgroup: root
  config_file: /etc/prometheus/prometheus.yml
  config: {}
  service:
    name: prometheus
    user: prometheus
    group: prometheus
  exporters:
    node:
      pkg:
        name: prometheus-node-exporter
      service: prometheus-node-exporter
